- name: check for project already created...
  stat: path=/vagrant/venv/{{ project_name }}
  register: mdotproj

- name: create project...
  command: /vagrant/venv/bin/django-admin.py startproject {{project_name }} chdir=/vagrant/venv/
  when: not mdotproj.stat.exists
