
    - name: install mdot from github...
      pip: name={{ item }} virtualenv={{ virtualenv_path }}
      ignore_errors: yes
      when: not notinitial.stat.exists
      with_items:
        - git+https://github.com/uw-it-aca/mdot/#egg=mdot
        - git+https://github.com/uw-it-aca/mdot-rest/#egg=mdot_rest
        - git+https://github.com/uw-it-aca/mdot-developers.git#egg=mdotdevs

    - name: checkout develop branch of repositories...
      git: repo={{ item }} clone=no update=no version=develop
      when: not notinitial.stat.exists
      with_items:
        - https://github.com/uw-it-aca/mdot-rest.git
        - https://github.com/uw-it-aca/mdot.git
        - https://github.com/uw-it-aca/mdot-developers.git
