---
- hosts: all
  vars:
    settings_secret_key: "{{ lookup('password', playbook_dir + '/generated/secretkey chars=ascii_letters,digits,hexdigits,punctuation') }}"
    mysql_root_password: "{{ lookup('password', playbook_dir + '/generated/mysqlrt chars=ascii_letters,digits,hexdigits,punctuation') }}"
    mysql_app_password: "{{ lookup('password', playbook_dir + '/generated/mysqlapp chars=ascii_letters,digits,hexdigits,punctuation') }}"

  tasks:

    - include: tasks/initial.yml

    - include: tasks/apt_system.yml

    - include: tasks/apt_virtualenv.yml

    - include: tasks/npm.yml

    - include: tasks/apt_git.yml

    - include: tasks/app.yml

    - include: tasks/create_proj.yml

    - include: tasks/django_utils.yml

    - include: tasks/precommit_hook.yml

    - include: tasks/apt_mysql.yml

    - name: Install mysql-python...
      pip: name=mysql-python virtualenv=/vagrant/venv

    - include: tasks/migrate_database.yml

    - name: template screenrc into home...
      template: src="templates/screenrc" dest="/home/vagrant/.screenrc"

    - name: template vimrc into home...
      template: src="templates/vimrc" dest="/home/vagrant/.vimrc"
